### ISSUE TITLE
Mobile Device Issues

### ISSUE THREAD

**Issue by PRoryCallahan** [sjhuskey/ldlt#1]
When viewed on mobile, the labels for speakers collapse on top of the text (screenshot attached below). I'm not sure if this requires a fix in your "tei-html.css" file for "tei-label" or "speaker". One solution would be to place speaker in separate column. Another would be to alter the margin/padding.

I took a look at settings as well for "tei-head" to see why the title was creating the line break but couldn't immediately see why. It's not an issue when viewed on desktop.

The nav icon isn't opening.

Right control panel appears to break the nav header. A possible solution here would be to have the control panel collapse on mobile devices and turn into a sticky header placed under main nav.

I'm happy to help as I can if these are issues you wish to address.

<img width="372" alt="Screen Shot 2022-03-31 at 11 41 35 PM" src="https://user-images.githubusercontent.com/52117304/161196131-c10759f8-2ad8-4cb4-a5f1-3edbd92f9d4c.png">

**Comment by sjhuskey** [comment]
Thanks for the feedback! We had to move this site to another server in a hurry, so there wasn't much time for testing. We also changed the architecture and platform of the site, so it's no wonder that there are problems. 

The site has always been primarily oriented toward desktop use, since the layout requires quite a lot of space, but we've been wanting to work on a mobile version. If you have ideas for the mobile version, please feel free to send your suggestions.

**Comment by PRoryCallahan** [comment]
It's my pleasure. I love what you are doing with the LDLT and I certainly understand how desktop is the optimum viewing environment. I'm hitting the crunch part of the semester, but if you are looking for people to test the site as you finish the migration, I would love be notified of ways I might provide useful feedback, especially once May comes around.
